# Generated by Django 5.2.1 on 2025-06-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='classroom_name',
            new_name='classroom',
        ),
    ]
