# Generated by Django 5.2.2 on 2025-09-12 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_submission_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviouralSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(choices=[('Punctuality', 'Punctuality'), ('Neatness', 'Neatness'), ('Attentiveness', 'Attentiveness'), ('Social Development', 'Social Development'), ('Assignment', 'Assignment'), ('Class Participation', 'Class Participation'), ('Perseverance', 'Perseverance'), ('Responsibility', 'Responsibility'), ('Politeness', 'Politeness'), ('Honesty', 'Honesty'), ('Sport & Games', 'Sport & Games'), ('Club Participation', 'Club Participation'), ('Psychomotor', 'Psychomotor')], max_length=50)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioural_skills', to='portal.gradereport')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'report', 'skill_name')},
            },
        ),
    ]
