# Generated by Django 5.2.1 on 2025-06-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_classroom_name_user_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.classroom'),
        ),
    ]
