# Generated by Django 5.2.1 on 2025-05-22 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_body_announcement_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
