# Generated by Django 5.2.4 on 2025-07-08 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_subjectgrade_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgrade',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='first_term_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='grade_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='second_term_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('total_available_score', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('overall_average', models.FloatField(blank=True, null=True)),
                ('overall_position', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('next_term_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'term', 'session')},
            },
        ),
    ]
