# Generated by Django 5.2.4 on 2025-07-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_subjectgrade_average_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgrade',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='next_term_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.classroom'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.classroom'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.classroom'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.classroom'),
        ),
    ]
