# Generated by Django 5.2.4 on 2025-07-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_subjectgrade_admin_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentReport',
        ),
    ]
