# Generated by Django 5.2.1 on 2025-05-24 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_rename_created_at_resource_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
