# Generated by Django 5.2.1 on 2025-05-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student_class',
            field=models.CharField(blank=True, help_text='Class this assignment is for (optional if assigned to individual student)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
