# Generated by Django 5.2.2 on 2025-07-31 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_subjectgrade_admin_comment_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
                ('session', models.CharField(max_length=20)),
                ('total_available_score', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('overall_average', models.FloatField(blank=True, null=True)),
                ('overall_position', models.CharField(blank=True, max_length=10)),
                ('teacher_comment', models.TextField(blank=True)),
                ('admin_comment_report', models.TextField(blank=True)),
                ('next_term_date', models.DateField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
