# Generated by Django 5.2.2 on 2025-07-31 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_studentreportsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectgrade',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='admin_comment_report',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='next_term_date',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='overall_average',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='overall_position',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='session',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='teacher_comment',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='term',
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='total_available_score',
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='exam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='first_test',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='grade_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='manual_grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='manual_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='second_test',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('total_available_score', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_average', models.FloatField(blank=True, null=True)),
                ('overall_position', models.CharField(blank=True, max_length=10)),
                ('teacher_comment', models.TextField(blank=True)),
                ('admin_comment_report', models.TextField(blank=True)),
                ('next_term_date', models.DateField(blank=True, null=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='portal.gradereport'),
        ),
        migrations.DeleteModel(
            name='StudentReportSummary',
        ),
    ]
