# Generated by Django 5.2.1 on 2025-05-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_assignment_student_class_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_class',
        ),
        migrations.AddField(
            model_name='announcement',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Optional – only needed if this announcement is class-specific', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.classroom'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Class this assignment is for (optional if assigned to individual student)', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.classroom'),
        ),
        migrations.AddField(
            model_name='resource',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Class this resource is for', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.classroom'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(default=1, help_text='Select the class this timetable belongs to', on_delete=django.db.models.deletion.CASCADE, to='portal.classroom'),
        ),
        migrations.AddField(
            model_name='user',
            name='Classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portal.classroom'),
        ),
    ]
