# Generated by Django 5.2.1 on 2025-05-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_classroom_remove_assignment_student_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Classroom',
            new_name='classroom',
        ),
    ]
