# Generated by Django 5.2.2 on 2025-07-31 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_subjectgrade_admin_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgrade',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades_direct', to=settings.AUTH_USER_MODEL),
        ),
    ]
