# Generated by Django 5.2.1 on 2025-05-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_rename_classroom_user_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
