# Generated by Django 5.2.1 on 2025-05-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_submission_score_submission_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
