# Generated by Django 5.2.2 on 2025-08-01 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_subjectgrade_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectgrade',
            options={'ordering': ['subject']},
        ),
        migrations.RemoveField(
            model_name='subjectgrade',
            name='comment',
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='session',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='term',
            field=models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='exam',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='first_term_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='first_test',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='manual_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='portal.gradereport'),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='second_term_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='second_test',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
