# Generated by Django 5.2.2 on 2025-08-01 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_subjectgrade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.classroom'),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='session',
            field=models.CharField(blank=True, choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gradereport',
            name='term',
            field=models.CharField(blank=True, choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='portal.gradereport'),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
