# Generated by Django 5.2.2 on 2025-08-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_gradereport_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectgrade',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
