# Generated by Django 5.2.1 on 2025-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_announcement_target_audience_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
