# Generated by Django 5.2.2 on 2025-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_subjectgrade_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradereport',
            name='date_uploaded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
