# Generated by Django 5.2.1 on 2025-06-03 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_announcement_target_audience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('first_test', models.PositiveIntegerField(default=0)),
                ('second_test', models.PositiveIntegerField(default=0)),
                ('exam', models.PositiveIntegerField(default=0)),
                ('term', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_grades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
