# Generated by Django 5.2.1 on 2025-06-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_alter_teacher_gender_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgrade',
            name='manual_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='manual_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
