# Generated by Django 5.2.1 on 2025-06-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_subjectgrade_manual_grade_subjectgrade_manual_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectgrade',
            name='exam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='first_test',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='second_test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
